---
- name: Debian - Add/Remove extra groups
  when: item.1.enabled
  group:
    name: "{{ item.1.name }}"
    state: "{{ item.1.state }}"
    gid: "{{ item.1.gid }}"
  loop: "{{ aspects_local_users_groups | default({}) | dictsort }}"
  tags:
    - aspects_local_users
    - aspects_local_users_groups