---
- name: Include init.yml when role is enabled.
  when: aspects_local_users_enabled
  include_tasks: init.yml
  tags:
    - aspects_local_users
    - aspects_local_users
    - aspects_local_users_groups_append
    - aspects_local_users_ssh_keys
